networks:
  gh_rapi-network:
    driver: bridge

volumes:
  gh_rapi-redis_data:
  gh_rapi-server_data:

services:
  gh_rapi-redis:
    image: redis:latest
    container_name: gh_rapi-redis
    restart: always
    volumes:
      - gh_rapi-redis_data:/data
    networks:
      - gh_rapi-network

  gh_rapi-server:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: gh_rapi-server
    environment:
      - GITHUB_REPOSITORY_OWNER=lvkaszus
      - GITHUB_REPOSITORY_NAME=asklvkaszus

      - REDIS_URI=redis://gh_rapi-redis:6379

      - FETCH_RATELIMIT_INTERVAL="100 per 12 hours"
      - UPDATE_RATELIMIT_INTERVAL="50 per 12 hours"

      - CORS_ORIGINS=http://localhost

      - WEBHOOK_SECRET=5bb657a67821cdf57aa763475770d6911b03400fe726a7459c06948180ca017c     # Linux: `openssl rand -hex 32`
      - CUSTOM_WEBHOOK_URL_PATH=fd7a4948b1a8f06382fc4c3d6e982f57                            # Linux: `openssl rand -hex 16`
    restart: always
    volumes:
      - gh_rapi-server_data:/data
    networks:
      - gh_rapi-network
    ports:
      - 127.0.0.1:8000:8000
    depends_on:
      - gh_rapi-redis
